### ISSUE TITLE
[🐛]

### ISSUE THREAD

**Issue by imivotteler** [snyk-tech-services/snyk-user-sync-tool#79]
- `node -v`:  v12.22.9
- `npm -v`: 8.5.1
- OS: Ubuntu
- Command run: DEBUG=-': DEBUG=* snyk-user-sync-tool --v2 --dry-run --membership-file=snyk_import.json --add-new --delete-missing --api-keys <MY-VALID-KEY>

### Expected behaviour
The dry run mode of the script starts running, informing me of which accounts will be added and which will be removed, alongside the org/group ID. 

### Actual behaviour
```
snyk ERROR: ApiAuthenticationError: AxiosError: Request failed with status code 401
    at Object.makeSnykRequest (/usr/local/lib/node_modules/snyk-user-sync-tool/node_modules/snyk-request-manager/src/lib/request/request.ts:87:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  data: {
    code: 401,
    message: 'Invalid auth token provided',
    error: 'Invalid auth token provided'
  }


 snyk:snykGroupsMetadata we are handling generic error +0ms
  snyk:app groupsMetadata: {
  snyk:app   "snykKeys": "<redacted UUID value>",
  snyk:app   "_groupsMetadata": [
  snyk:app     {
  snyk:app       "groupName": "<redacted UUID value>",
  snyk:app       "groupId": "",
  snyk:app       "groupStatus": "disabled",
  snyk:app       "groupStatusReason": "AxiosError: Request failed with status code 401"
  snyk:app     }
  snyk:app   ],
  snyk:app   "_buffer": 250
  snyk:app } +0ms
  snyk:app pendingInvites: [] +9ms
Pending invites found: 0
  snyk:app processing v2 format +0ms
  snyk:app sourceGroups: undefined +2ms
error processing source data: Cannot read property 'length' of undefined

```

### Steps to reproduce
Create an Org Admin API key in the Snyk UI
Create a json file in the expected format; eg:

```
[
    {
        "userEmail": "someuser@somewhere.com",
        "role": "Org Collaborator",
        "org": "account-recovery",
        "group": "OVO Group"
    },
    {
        "userEmail": "otheruser@something.net",
        "role": "Org Collaborator",
        "org": "account-recovery",
        "group": "OVO Group"
    }
]
```

### Debug log
See above

**Comment by imivotteler** [comment]
The key i've created has the highest level of permissions in Snyk so I don't know why i'm getting a 401.

**Comment by scott-es** [comment]
hello @imivotteler , the tool operates at the group level, managing org memberships across it.  It looks like you are using an ORG level admin token, rather than a GROUP level admin token.

**Comment by imivotteler** [comment]
Hi @scott-es - had my hopes up then! The key i'm using is already a group admin level token. Do  you have any other suggestions? I'm the service owner for snyk so in my frustration I created a service account with this highly permissive key.

**Comment by scott-es** [comment]
Its not replicable, and the error is pretty clear indicator that the provided tokens are not group admin.  Could I respectfully ask that you double check that before we start looking at other possibilities ?

**Comment by scott-es** [comment]
Could you share how you are passing the API keys in (without exposing the token).  The `groupName` in the error output doesn't look right (it should not be a UUID) and `groupId` is blank which should be the UUID

**Comment by scott-es** [comment]
I hope that's not the token you put in the comment!!!

**Comment by imivotteler** [comment]
> Also could you share how you are passing the API keys in (without exposing the token). The `groupName` in the error output doesn't look right (it should not be a UUID) and `groupId` is blank which should be the UUID

I'm specifying the key using the --api-keys argument, and have tried surrounding the key in quotes and without. The key i've created has the Group Admin role. It's not the one I shared in the original issue. 

Not sure where the groupid in the error is coming from - the only thing relating to groups that i'm providing is in the 'group' key in the JSON which gets ingested. Thanks so much!

**Comment by imivotteler** [comment]
Started again with a fresh clone of this tool from the repo in case there were some residual files somewhere providing that groupID and groupName but alas, I can't see where those two UUIDs are coming from. 

I also recreated my Snyk service account key with the Group Admin role, and I tried the key attached to my own user profile both with the same 401

```
data: {
    code: 401,
    message: 'Invalid auth token provided',
    error: 'Invalid auth token provided'
  }
```


Do you have any other suggestions for avenues to investigate @scott-es? Sadly I don't have any other logs to delve into other than those provided already.

**Comment by scott-es** [comment]
first of all I just realized your avatar is zero cool from hackers.  kudos for that.

regarding specification of the group and token, the two ways are:

1. use environment variable, e.g.
`export SNYK_IAM_API_KEYS='<group name>':<group key>,'<group name>':<group key>`

You need both `<group name>` and `<group key>`, notice that `<group name>` is in single quotes.

2. use --api-keys , e.g.
`--api-keys='<group name>':<group key>,'<group name>':<group key>`

Please note, there are single quotes around the group name and the group name and the key are separated by a colon.  separate more than one group by a comma.

something must be wrong in the value you are setting here since your groupName value shows a UUID, rather than the actual name.  Here's what my debug output looks like:
```
{
     groupName: 'Customer Success Engineering',
     groupId: '',
     groupKey: '<redacted>',
     groupStatus: 'disabled',
     groupStatusReason: 'AxiosError: Request failed with status code 401'
}
```
I'm not sure why groupId is blank here, a when i set the correct key the script works anyway.  That should not be any real issue.

the value of snykKeys in the debug out put should also represent the group name:group key value, like this:

`"snykKeys": "Customer Success Engineering:<redacted UUID value>"` so I think thats definitive evidence you're only providing the key (token) and not the group name as well in the expected format.

Can you look at how you are setting --api-keys and/or the environment variable SNYK_IAM_API_KEYS and make sure its matching whats expected?

On a side note, I'm worred the UUID value for `groupId` in your issue description is actually a token. Please edit and redact that if thats the case and make sure to delete that token.

**Comment by scott-es** [comment]
i redacted in the original just in case

**Comment by scott-es** [comment]
are you still having an issue @imivotteler ?
